name: Docker Image CI
# Triggers para hacer el cambio
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        
      # La tuberia (|) significa que cada una de las lineas que 
      # incluyamos se ejecutara de manera independiente
      run: | 
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p DOCKER_PASSWORD
        echo "Fin del login"

        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
